theme: jekyll-theme-time-machine 

Nama-nama Hewan laut,Bumbu dan sayuran dalam bahasa Biak

 Cakalang (Inburnose)
2.Ikan Kaka Tua (Indakmas)
3.Ikan Samandar (Indadwar)
4.Ikan Julung (Insnayur)
5.Ikan Oci (Ingur)
6.Ikan Goropa (Indaf)
7.Ikan Bubara (Ingarpu)
8.Ikan Kumis (Inparga)
9.Ikan Sako (Imbekwan)
10.Bia Jari-jari (Kakawai)
11.Cumi-cumi (Suntung)
12.Gurita (Kais)
13.Udang laut (Amos)
14.Ketang Kenari (Amyaiw)

Nama-nama Bumbu
1.Kunyit (Andefun)
2.Rica (Marisan)
3.Bawang Merah (Bawang Berike)
4.Bawang Putih (Bawang Bepyoper)
5.Jahe (Konsop)
6.Serei (Ampui)
7.Garam (Karuimasen)
