theme: jekyll-theme-time-machine 

Nama-nama Hewan laut,Bumbu,sayuran dan buah dalam bahasa Biak

 Cakalang (Inburnose)
2.Ikan Kaka Tua (Indakmas)
3.Ikan Samandar (Indadwar)
4.Ikan Julung (Insnayur)
5.Ikan Oci (Ingur)
6.Ikan Goropa (Indaf)
7.Ikan Bubara (Ingarpu)
8.Ikan Kumis (Inparga)
9.Ikan Sako (Imbekwan)
10.Bia Jari-jari (Kakawai)
11.Cumi-cumi (Suntung)
12.Gurita (Kombrof)
13.Udang laut (Amos)
14.Ketam Kenari (Amyaiw)
15.Kepiting (Kaf)
16.Kerang (Babasya)
17.Teripang (Kamboa)

Nama-nama Bumbu
1.Kunyit (Andefun)
2.Rica (Marisan)
3.Bawang Merah (Bawang Berike)
4.Bawang Putih (Bawang Bepyoper)
5.Jahe (Konsop)
6.Serei (Ampui)
7.Garam (Karuimasen)
8.Lengkuas (Arar)
9.Pandan (Eben)
10.Kencur (Daw)

Sayur-Mayur (Wei)
1.Sayur Sawi (Ram Sawi)
2.Sayur Bayam (Ram Bayam)
3.Sayur Kol (Ram Kol)
4.Sayur Kacang panjang (Ram kacang Panjang)
5.Sayur Kangkung (Ram Kangkung)
6.Sayur Bayam Merah (Ram Bayam Merah)
7.Sayur pepaya + petatas (Ransyokado)
8.Sayur Boncis (Ram Boncis)
9.Sayur Bambu (Rebun)

Buah-buahan (Aibon)
1.Cempedak (Andik)
2.Jambu (Amyui)
3.Jambu Manis (Amir)
4.Kurma (Aryawo)
5.Mangga (Away)
6.Kelapa Mudah (srai Bekamas)
7.Kelapa tua (Srai mas)
8Jeruk (Camfus)
