theme: jekyll-theme-time-machine 

Nama-nama Hewan laut dalam bahasa Biak

 Cakalang (Inburnose)
2.Ikan Kaka Tua (Indakmas)
3.Ikan Samandar (Indadwar)
4.Ikan Julung (Insnayur)
5.Ikan Oci (Ingur)
6.Ikan Goropa (Indaf)
7.Ikan Bubara (Ingarpu)
8.Ikan Kumis (Inparga)
9.Ikan Sako (Imbekwan)
10.Bia Jari-jari (Kakawai)
11.Cumi-cumi (Suntung)
12.Gurita (Kais)
13.Udang laut (Amos)
14.Ketang Kenari (Amyaiw)

